name: Aniwhere CI/CD 구축

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 소스코드 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 Version 설치하기
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: application.yml 파일 작성하기
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml

      - name: 실행 권한 부여
        run: chmod +x ./gradlew

      - name: gradlew wrapper 생성하기
        run: gradle wrap

      - name: 테스트 코드가 없으므로 해당 과정을 제외하고 빌드하기
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 쉽게 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./aniwhere.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./aniwhere.jar
          target: /home/ubuntu/Aniwhere-BE/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            rm -rf /home/ubuntu/Aniwhere-BE/current                                           
            mkdir /home/ubuntu/Aniwhere-BE/current                                                
            mv /home/ubuntu/Aniwhere-BE/tobe/aniwhere.jar /home/ubuntu/Aniwhere-BE/current/aniwhere.jar   
            cd /home/ubuntu/Aniwhere-BE/current
            sudo fuser -k -n tcp 8080 || true 
            nohup java -jar aniwhere.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/Aniwhere-BE/tobe